modules/song/controllers/DefaultController.php
<?php

namespace app\modules\song\controllers;

use Yii;
use app\modules\song\models\Song;
use app\modules\song\models\SongSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;

/**
 * DefaultController implements the CRUD actions for Song model.
 */
class DefaultController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Song models.
     * @return mixed
     */
    public function actionIndex()
    {
        // $searchModel = new SongSearch();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        // return $this->render('index', [
            // 'searchModel' => $searchModel,
            // 'dataProvider' => $dataProvider,
        // ]);
        return $this->redirect(['site/index']);

    }

    /**
     * Displays a single Song model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Song model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Song();

        if ($model->load(Yii::$app->request->post())) {
        	// echo "<pre>";print_r(Yii::$app->request->post());die;
        	$model->slug =  $model->to_slug(Yii::$app->request->post()['Song']['title']);

        	$model->lyric = html_entity_decode(Yii::$app->request->post()['Song']['lyric']);
        	$model->created_date = date('Y-m-d H:i:s');
        	$model->created_by = Yii::$app->user->getId();
        	$model->updated_date = date('Y-m-d H:i:s');
        	$model->updated_by = Yii::$app->user->getId();
        	if($model->save()){
	            return $this->redirect(['view', 'id' => $model->id]);
        	}
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Song model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
        	$model->slug =  $model->to_slug(Yii::$app->request->post()['Song']['title']);
        	$model->lyric = html_entity_decode(Yii::$app->request->post()['Song']['lyric']);
        	$model->updated_date = date('Y-m-d H:i:s');
        	$model->updated_by = Yii::$app->user->getId();
        	if($model->save()){
	            return $this->redirect(['view', 'id' => $model->id]);
	        }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Song model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Song model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Song the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Song::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
    public function actionTest()
    {
        return $this->render('test');
    }
}

modules/song/views/default/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;
use yii\helpers\ArrayHelper;
use app\modules\type\models\Type;
use app\modules\topic\models\Topic;
use kartik\select2\Select2;
use yii\web\JsExpression;
use yii\bootstrap4\Modal;
 

/* @var $this yii\web\View */
/* @var $model app\modules\song\models\Song */
/* @var $form yii\widgets\ActiveForm */
$get_arr_type = ArrayHelper::map(type::find()->all(),'id','type_name');
$get_arr_topic = ArrayHelper::map(topic::find()->all(),'id','topic_name');
if (Yii::$app->requestedRoute != 'song/default/create'){
    $save = "Cập nhật";
    $class = "btn btn-primary my-3 btn-sm";
}else{
    $save = "Thêm bài hát";
    $class = "btn btn-success my-3 btn-sm";
}
?>

<!-- Page content -->
    <div class="container-fluid mt--6">
      <div class="card mb-4">
        <!-- Card header -->
        <div class="card-header">
          <h3 class="mb-0">Thêm bài hát mới</h3>
        </div>
        <!-- Card body -->
        <div class="card-body">
    <?php $form = ActiveForm::begin(); ?>
          <!-- Form groups used in grid -->
          <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'title',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="song-title">Tên bài hát</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->textInput(['maxlength' => true,'placeholder' => "Tiêu đề bài hát"]) ?>

            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'key_chord',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="key-chord">Hợp âm chủ</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->textInput(['maxlength' => true,'placeholder' => "G,A,C..."]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'type_id',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="song-type_id">Thể loại</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->dropDownList(
                    $get_arr_type,
                     ['prompt'=>'Chọn thể loại']); ?>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
            <?= $form->field($model, 'first_lyric',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="first_lyric">Lời đầu bài hát</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->textInput(['maxlength' => true,'placeholder' => "Lời 1 của bài hát."]) ?>
            </div>
            <div class="col-md-4">
            <?= $form->field($model, 'chorus',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="chorus">Điệp khúc</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->textInput(['maxlength' => true,'placeholder' => "Câu đầu tiên của điệp khúc."]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'topic_id',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="song-topic_id">Chủ đề</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->dropDownList(
                    $get_arr_topic,
                     ['prompt'=>'Chọn chủ đề']); ?>
            </div>
          </div>
          <div class="row">
            <div class="col-6">
                <?= $form->field($model, 'tempo',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="tempo">Tốc độ bài hát (bmp)</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->textInput(['maxlength' => true,'placeholder' => "120"]) ?>
            </div>
            <div class="col-6">
                <?= $form->field($model, 'link_song',[ 'template' => '
                    <div class="form-group">
                        <label class="form-control-label" for="link_song">Link bài hát</label>
                        {input}
                    </div>
                    <div class="text-danger">{error}</div>'
                             ])->textInput(['maxlength' => true,'placeholder' => "VD: https://www.youtube.com/watch?v=XNswhKgId1Y"]) ?>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <div class="form-group">
                 <!-- Text editor -->
                    <label class="form-control-label" for="song-lyric">Nội dung bài hát</label>
                     <?= $form->field($model, 'lyric')->widget(CKEditor::className(), [
                        'options' => ['rows' => 6],
                        'preset' => 'basic',
                    ])->label(false) ?>
                    <?= Html::submitButton(Yii::t('app', $save), ['class' => $class]) ?>
                    <?php if (Yii::$app->requestedRoute == 'song/default/create'){ ?>
                    <?= Html::resetButton(Yii::t('app','Reset'), ['class' => 'btn btn-primary my-3 btn-sm']) ?>
                    <?php } ?>
                    <a href="<?php echo Yii::$app->urlManager->createUrl('site/index'); ?>" class="btn btn-close btn-sm"><span class="glyphicon glyphicon-chevron-left"></span> Thoát</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    <?php ActiveForm::end(); ?>

modules/song/views/default/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\song\models\SongSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="song-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'key_chord') ?>

    <?= $form->field($model, 'type_id') ?>

    <?php // echo $form->field($model, 'first_lyric') ?>

    <?php // echo $form->field($model, 'chorus') ?>

    <?php // echo $form->field($model, 'topic_id') ?>

    <?php // echo $form->field($model, 'tempo') ?>

    <?php // echo $form->field($model, 'link_song') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'create_by') ?>

    <?php // echo $form->field($model, 'update_date') ?>

    <?php // echo $form->field($model, 'update_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/song/views/default/create.php
-+<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\song\models\Song */

$this->title = Yii::t('app', 'Thêm bài hát mới');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Songs'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
</div>
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0"><?= Html::encode($this->title) ?></h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="<?php echo Yii::$app->urlManager->createUrl('site/index'); ?>">Bài hát</a></li>
                  <li class="breadcrumb-item active" aria-current="page"><?= Html::encode($this->title) ?></li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

modules/song/views/default/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\ArrayHelper;
use app\modules\type\models\Type;
use app\modules\topic\models\Topic;
use app\modules\song\models\Song;
use yii\helpers\Url;

// echo "<pre>";print_r($this);die;
$this->title = 'List Song';

// $get_arr_type = ArrayHelper::map(type::find()->all(),'id','type_name');
$get_arr_song = song::find()->select(['id','title','first_lyric','chorus','type_id','key_chord'])->all();
// echo "<pre>";print_r($get_arr_song);die;
$i = 1;

?>
<!-- Header -->
<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">Bài Hát</h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item"><a href="<?php echo Yii::$app->urlManager->createUrl('song/default/index'); ?>">Bài Hát</a></li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <?php if(Yii::$app->user->getId()!=1){ ?>
          <a href="<?php echo Yii::$app->urlManager->createUrl('song/default/create'); ?>" class="btn btn-sm btn-neutral"><i class="ni ni-fat-add mr-0"></i> <span class="d-none d-md-inline">Thêm bài hát</span></a>
          <?php } ?>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card">
        <!-- Card header -->
        <div class="card-header">
          <h3 class="mb-0">Danh sách bài hát</h3>
        </div>
        <div class="table-responsive py-4">
          <table class="table table-flush" id="datatable-basic">
            <thead class="thead-light">
              <tr>
                <th>#</th>
                <th>Tên bài hát</th>
                <th>Lời đầu</th>
                <th>Điệp khúc</th>
                <th>Tone chính</th>
                <th>Thể loại</th>
                <th></th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>#</th>
                <th>Tên bài hát</th>
                <th>Lời đầu</th>
                <th>Điệp khúc</th>
                <th>Tone chính</th>
                <th>Thể loại</th>
                <th></th>
              </tr>
            </tfoot>
            <tbody>
                <?php foreach ($get_arr_song as $song) { 

                // echo "<pre>";print_r($song['title']);die;
                    // echo $song['title'];die;
                ?>
              <tr>
                <td><?php echo $i ?></td>
                <td>
                  <a href="<?php echo Url::to(['default/view', 'id' => $song['id']]); ?>" class="font-weight-bold"><?php echo $song['title']; ?></a>
                </td>
                <td>
                  <a href="../BNNS/song.html"><?php echo $song['first_lyric']; ?>...</a>
                </td>
                <td>
                  <a href="../BNNS/song.html"><?php echo $song['chorus']; ?>...</a>
                </td>
                <td>
                  <a href="#!"><?php echo $song['key_chord']; ?></a>
                </td>
                <td>
                  <a href="#!"><?php $type = type::find()->select('type_name')->where(['id' => $song['type_id']])->one();
                  if(empty($type['type_name'])){
                    echo "<span style='color:red;'>Chưa cập nhật</span>";
                  }else{
                      echo $type['type_name']; 
                  }
                  ?></a>

                </td>
                <td class="text-right">
                  <div class="dropdown">
                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                      <a class="dropdown-item" href="<?php echo Url::to(['default/view', 'id' => $song['id']]); ?>">Chi tiết</a>
                      <a class="dropdown-item" href="<?php echo Url::to(['default/update', 'id' => $song['id']]); ?>">Sửa</a>
                      <a class="dropdown-item" href="<?php echo Url::to(['default/delete', 'id' => $song['id']]); ?>">Xóa</a>
                    </div>
                  </div>
                </td>
              </tr>
                <?php $i++;
                 } ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

modules/song/views/default/test.php
xin chao

modules/song/views/default/update.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\modules\song\models\Song */

$this->title = Yii::t('app', 'Sửa bài hát: {name}', [
    'name' => $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Songs'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
    <div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-8 col-9">
              <h6 class="h2 text-white d-inline-block mb-0"><?= Html::encode($this->title) ?></h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="<?php echo Yii::$app->urlManager->createUrl('song/default/index'); ?>"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="<?php echo Url::to(['default/view', 'id' => $model->id]); ?>">Bài hát</a></li>
                  <li class="breadcrumb-item active" aria-current="page"><?= Html::encode($this->title) ?></li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

modules/song/views/default/view.php
<?php

use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use app\modules\user\models\User;

$getusernumber = new User;

$getuser = $getusernumber->getusernumber();


/* @var $this yii\web\View */
/* @var $model app\modules\song\models\Song */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Songs'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="header bg-primary pb-6">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7"style="z-index: 999;">
              <h6 class="h2 text-white d-inline-block mb-0"><?= Html::encode($this->title) ?></h6>
              <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                  <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
                  <li class="breadcrumb-item"><a href="<?php echo Yii::$app->urlManager->createUrl('site/index'); ?>"><?php echo Yii::t('app','List of songs') ?></a></li>
                  <li class="breadcrumb-item active" aria-current="page"><?= Html::encode($this->title) ?></li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
<!-- Header -->
    <div class="container-fluid mt--9">
<div id="invoice">
    <div class="toolbar hidden-print row">
        <?php if(!Yii::$app->user->getIsGuest()){ ?>
        <div class="col-lg-12 col-md-5 col-12 text-right">
          <?php if(Yii::$app->user->getId()!=$getuser){ ?>
            <div class="mb-2 mt-4 my-md-auto d-inline pr-md-1">
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
            <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
            'confirm' => Yii::t('app', 'Are you sure you want to delete this song?'),
            'method' => 'post',
            ],
            ]) ?>
            </div>
          <?php } ?>
            <div class="d-none d-lg-inline pl-md-1">
            <button id="printInvoice" class="btn btn-secondary" onclick="printJS({
            printable: 'song',//chọn id cần in
            type: 'html',
            header: '<?= Html::encode($this->title) ?>',
            css: ['<?php echo Yii::getAlias('@web').'/dist/css/style.css' ?>','<?php echo Yii::getAlias('@web').'/dist/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css' ?>','<?php echo Yii::getAlias('@web').'/dist/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' ?>','<?php echo Yii::getAlias('@web').'/dist/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css' ?>','<?php echo Yii::getAlias('@web').'/dist/css/argon.css' ?>'], //Thêm css
            ignoreElements:['show_hide','transposition','title-song'], //loại trừ các element id này
            style: 'div#lyric p,div#lyric span{font-size:30px}span.verse,span.note-lyric{display:none}.name a{font-size:30px;text-decoration:none;font-weight:300;color:blue}'// chỉnh sửa lại một số css không hiển thị tốt
            })"><i class="fa fa-print"></i> <?php echo Yii::t('app','Print') ?></button>
            <button class="btn btn-secondary" onclick="exportPdf(<?php $model->title ?>)"><i class="fa fa-file-pdf-o"></i> <?php echo Yii::t('app','Export as PDF') ?></button>
            </div>
        </div>
          <?php } ?>
        <hr>
    </div>
    <div class="invoice overflow-auto" id="song">
        <div class="min-md-width">
            <header>
                <div class="row">
                    <div class="col">
                        <div class="title" id="title-song">
                            <h1><?= $this->title ?></h1>
                        </div>
                        <h2 class="name">
                            <a target="_blank" href="#">
                                <?php echo Yii::t('app','Key Primary') ?>: <?= $model->key_chord ?>
                            </a>
                        </h2>
                        <button class="btn btn-info" id="show_hide"><?php echo Yii::t('app','Hide chords') ?></button>
                    </div>
                </div>
            </header>
            <main>
                <div class="row">
                    <div class="col-12 song" id="lyric">
                        <div id="transposition" class="transposition"></div>
                        <?= Html::decode($model->lyric) ?>
                    </div>
                </div>
            </main>
            <footer>
                <a class="btn btn-outline-dark btn-sm float-left" href="<?php echo Yii::$app->urlManager->createUrl('site/index'); ?>"><i class="ni ni-bold-left"></i> <?php echo Yii::t('app','Back') ?></a>
                <?php  $user = user::find()->select('username')->where(['id' => $model->created_by])->one(); ?>
                <?php echo Yii::t('app','Posted by') ?>: <?php echo $user['username']; ?>
            </footer>
        </div>
        <!--DO NOT DELETE THIS div. IT is responsible for showing footer always at the bottom-->
    </div>
</div>
</div>
<!-- <div class="song-view">

    <h1></h1>

    <p>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'title',
            'lyric',
            'key_chord',
            'type_id',
            'first_lyric',
            'chorus',
            'topic_id',
            'tempo',
            'link_song',
        ],
    ]) ?>

</div>
 -->